/**:
    ros__parameters:

    # cloud_to_scan
      mapgrid/Horizon_SCAN: 1800
      mapgrid/angle_max_: 3.141592653589793
      mapgrid/angle_min_: -3.141592653589793
      mapgrid/delta_pi: 0.0034906585
      mapgrid/groundScanInd: 8
      mapgrid/range_max_: 100.0
      mapgrid/range_min_: 0.1
      mapgrid/scan_time: 0.1
      use_sim_time: false

    # OccupanyMapping
      mapgrid/mapParams/height: 2000
      mapgrid/mapParams/log_free: -1.0
      mapgrid/mapParams/log_occ: 2.0
      mapgrid/mapParams/offset_x: 1250
      mapgrid/mapParams/offset_y: 1250
      mapgrid/mapParams/origin_x: 0.0
      mapgrid/mapParams/origin_y: 0.0
      mapgrid/mapParams/resolution: 0.05
      mapgrid/mapParams/width: 2000
      mapgrid/mapParams/update_scope: 20.0  
      # use_sim_time: false
