/**:
  ros__parameters:
    empty_map/delta_x: 5.0 #虚拟框垂直于起终点连线方向的距离
    empty_map/delta_y: 5.5 #虚拟框到起终点连线方向的距离
    empty_map/size_x: 8.0 #空地图的width方向扩充
    empty_map/size_y: 8.0 #空地图的height方向扩充
    empyt_map/pub_hz: 2 #发布频率


