/**:
    ros__parameters:
      local_inscribed_radiu: 0.04 #膨胀半径 0.01
      local_cost_scaling_factor: 10.0 #代价因子 10.0
      local_distance_: 2.0 #local_width = local_height = (distance * 2.0) / resolution; 1.0
      local_resolution: 0.05 #地图分辨率 0.02

      global_inscribed_radiu: 0.35 #膨胀半径 0.15
      global_cost_scaling_factor: 10.0 #代价因子
      global_distance_: 2.5 #代价因子
      global_resolution: 0.05 #地图分辨率

      footprint_length: 0.40 #检测障碍物，单根线的长度
      footprint_height: 0.15 #检测障碍物，相邻两根线的宽度
      obstacles_depth: -0.4 #检测障碍物，以激光雷达原点下探的深度
      yaml_filename: "/home/zeen/unitree_ws/install/task/share/task/maps/map/default.yaml" #栅格地图的读取路径

      #Point cloud removal around the back of dog's body
      remove_Width: 0.35 # Half the actual width
      remove_Height: 0.60
